### ISSUE TITLE
Redesign analytics page, add graphs, & add more data

### ISSUE THREAD

**Issue by ashleyfae** [ashleyfae/book-database#161]
- [x] Number of new books obtained
- [x] Most read genre
- [ ] Book that's been re-read the most
- [x] Number of books read in each format 
- [x] For the selected time period: breakdown of books grouped by their publication year
- [ ] Series: (pie) # books in a series / standalones
- [ ] Series: (pie) 1st book in series, 2nd book in series, 3rd book in series, 4th+
- [x] Series: Number of different series

# All time graphs

## Bar graph - books per year

![Screenshot from 2019-10-27 08-41-40](https://user-images.githubusercontent.com/6324272/67632010-9e3b1b00-f895-11e9-933c-a15b227cff4d.png)

## Bar graph - pages per year

![Screenshot from 2019-10-27 08-42-03](https://user-images.githubusercontent.com/6324272/67632016-abf0a080-f895-11e9-80bd-60740a57e409.png)

## Line or bar - books over time (per month)

![Screenshot from 2019-10-27 08-42-36](https://user-images.githubusercontent.com/6324272/67632025-c1fe6100-f895-11e9-9f97-36c452d4ba21.png)

**Comment by nosegraze** [comment]
- Add time period option for "all time".

Thinking of splitting the analytics page into different tabs.

## Overview

Probably contain this whole chunk:

![Screenshot from 2019-12-20 12-55-58](https://user-images.githubusercontent.com/6324272/71256245-18cd6780-2328-11ea-81f0-50a4c8b66e43.png)

- Overall - show number of books read, grouped by year (bar chart).

---

## Books

- Table of books being released in the chosen time period (max 20).

---

## Reading

- Most read genre (selected time period)
- Most read genre (all time)
- Most read publisher (selected time period)
- Most read publisher (all time)
- Table showing format breakdown (number of books read in each format)
- Breakdown of books grouped by their publication year
- Pages breakdown (existing table)
- Shortest book
- Longest book
- Rating breakdown (existing table)
- Bar chart showing books read over time.

---

## Reviews

- Table showing reviews written (existing table)
- Read but not reviewed (or should this go under Reading?)
- Bar chart showing reviews written over time.

---

## Editions

- Number of newly obtained books.
- Table showing books obtained.
- Book you own the most copies of (all time).
- Bar chart showing books acquired over time.

---

## Terms

- All existing term breakdowns would go here.

**Comment by nosegraze** [comment]
### Breakdown of how long it takes to read each book

```mysql
SELECT ROUND( AVG( DATEDIFF( date_finished, date_started ) * percentage_complete ) ) + 1 AS number_days, DATE_FORMAT( date_started, '%Y-%m-%d' ) AS date_started, book_id
FROM wp_bdb_reading_log
WHERE date_started IS NOT NULL
  AND date_finished IS NOT NULL
  AND percentage_complete >= 1
GROUP BY date_started
ORDER BY date_started ASC
```

To be put in a graph.

Exclude books that took longer than x weeks to read to exclude outliers.
